/** @mainpage Main
 *  @author Garrett Klatte
 *  @date 12/04/2015
 */

/** @file main.cpp
 *  @brief This is the default main.cpp generated by Qt Creator. Launches the mainwindow which allows the game to be played.
 */

#include "mainwindow.h"
#include "asteroid.h"
#include <QApplication>
#include <iostream>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();

    return a.exec();
}
